#pragma once

#include <stdlib.h>
#include <stdbool.h>
#include <setjmp.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>

#ifdef _WIN32
#define NORETURN _declspec(noreturn)
#else
#define NORETURN __attribute__((noreturn))
#endif

enum eErrorCode
{
	ERROR_NONE,

	// tokenizer errors
	ERROR_TOKENIZER_START,
	ERROR_MEMORY_ALLOC_FAILURE,
	ERROR_UNTERMINATED_STRING,
	ERROR_UNTERMINATED_ESC_SEQ,
	ERROR_UNKNOWN_ESC_SEQ,

	// parser errors
	ERROR_PARSER_START,
	ERROR_P_MEMORY_ALLOC_FAILURE,
	ERROR_UNTERMINATED_BLOCK_STMT,
	ERROR_UNTERMINATED_COMMAND_STMT,
	ERROR_INTERNAL_NOT_A_BLOCK_STMT,
	ERROR_INTERNAL_NOT_A_COMMAND_STMT,
	ERROR_EXPECTED_STATEMENT,
	ERROR_EXPECTED_OPEN_PAREN,
	ERROR_EXPECTED_CLOSE_PAREN,
	ERROR_EXPECTED_SEMICOLON,
	ERROR_EXPECTED_THEN,
	ERROR_EXPECTED_OPEN_BLOCK,
	ERROR_EXPECTED_CLOSE_BLOCK,
	ERROR_EXPECTED_SEMICOLON_OR_ARGUMENTS,
	ERROR_EXPECTED_CLOSE_PAREN_OR_ARGUMENTS,

	ERROR_END,
};

void LoadFile(const char* pfn);

